// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBTYwJJackNglWecpP-ZOnEiXJGBkrCEI',
    appId: '1:566392943700:android:40f95fb9c54c698cc469c1',
    messagingSenderId: '566392943700',
    projectId: 'gossip-45b0d',
    storageBucket: 'gossip-45b0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgrkMaevoiydUuPorzbq9B77_W7qImprk',
    appId: '1:566392943700:ios:26ceb5f6f0d5efbcc469c1',
    messagingSenderId: '566392943700',
    projectId: 'gossip-45b0d',
    storageBucket: 'gossip-45b0d.firebasestorage.app',
    androidClientId: '566392943700-0lf7r8ui3q4hhbf3ei3t8abcj847648d.apps.googleusercontent.com',
    iosClientId: '566392943700-kabsiscomdm6q5u5v9aae6rnc1vha75u.apps.googleusercontent.com',
    iosBundleId: 'com.example.gossipcom',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8D9TWAd7lUytopcX9k23fcckqzYI9B20',
    appId: '1:566392943700:web:33ec372a45a6aa93c469c1',
    messagingSenderId: '566392943700',
    projectId: 'gossip-45b0d',
    authDomain: 'gossip-45b0d.firebaseapp.com',
    storageBucket: 'gossip-45b0d.firebasestorage.app',
    measurementId: 'G-SCKC99XQFK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgrkMaevoiydUuPorzbq9B77_W7qImprk',
    appId: '1:566392943700:ios:26ceb5f6f0d5efbcc469c1',
    messagingSenderId: '566392943700',
    projectId: 'gossip-45b0d',
    storageBucket: 'gossip-45b0d.firebasestorage.app',
    androidClientId: '566392943700-0lf7r8ui3q4hhbf3ei3t8abcj847648d.apps.googleusercontent.com',
    iosClientId: '566392943700-kabsiscomdm6q5u5v9aae6rnc1vha75u.apps.googleusercontent.com',
    iosBundleId: 'com.example.gossipcom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8D9TWAd7lUytopcX9k23fcckqzYI9B20',
    appId: '1:566392943700:web:3b4b455601b6c593c469c1',
    messagingSenderId: '566392943700',
    projectId: 'gossip-45b0d',
    authDomain: 'gossip-45b0d.firebaseapp.com',
    storageBucket: 'gossip-45b0d.firebasestorage.app',
    measurementId: 'G-D5TXRKWVRB',
  );

}